services:
  - type: web
    name: dealership-backend
    env: python
    region: oregon  
    plan: free  
    buildCommand: |
      pip install -r server/requirements.txt
      python server/manage.py migrate
      python server/manage.py collectstatic --noinput
    startCommand: "gunicorn djangoproj.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: backend_url
        value: "https://xrwvm-fullstack-developer-capstone-helo.onrender.com"
      - key: sentiment_analyzer_url
        value: "https://sentianalyzer.1t3o0xexce5s.us-south.codeengine.appdomain.cloud"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    disk:
      name: sqlite-disk
      mountPath: /var/lib/sqlite
      sizeGB: 1  # 1GB free storage for SQLite

  - type: web
    name: dealership-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: "cd server/frontend && npm install && npm run build"
    startCommand: "npx serve -s build -l 3000"
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://xrwvm-fullstack-developer-capstone-helo.onrender.com"
